// Command generatebootstrap projects frozen captures into immutable bootstrap
// transport metadata. It never launches a browser or changes capture inputs.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/moreveal/mimic/chrome/152/generated"
	"github.com/moreveal/mimic/compatibility"
	"github.com/moreveal/mimic/internal/webapi"
)

func main() {
	check := flag.Bool("check", false, "check deterministic metadata without writing")
	flag.Parse()
	surface := &compatibility.WebAPISurface{GeneratedJavaScript: generated.Surface, GeneratedCatalogJSON: generated.SurfaceCatalog,
		Exposures: map[string]compatibility.RealmExposure{
			"window.insecure.non-isolated": generated.InsecureWindowExposure(),
			"window.secure.non-isolated":   generated.SecureWindowExposure(),
			"window.secure.isolated":       generated.SecureIsolatedWindowExposure(),
		}}
	var source bytes.Buffer
	source.WriteString("// Code generated by go run ./tools/generatebootstrap; DO NOT EDIT.\npackage generated\nimport \"github.com/moreveal/mimic/compatibility\"\nvar BootstrapMetadata = map[string]compatibility.BootstrapMetadata{\n")
	for _, name := range []string{"window.insecure.non-isolated", "window.secure.non-isolated", "window.secure.isolated"} {
		_, exposure, catalog := webapi.BootstrapFor(surface, name)
		fmt.Fprintf(&source, "%q: {ExposureJSON: %q, CatalogJSON: %q},\n", name, exposure, catalog)
	}
	source.WriteString("}\nvar BootstrapEventAttributes = []string{\n")
	var specs []struct{ Members []struct{ Name, Kind string } }
	if err := json.Unmarshal([]byte(generated.SurfaceCatalog), &specs); err != nil {
		panic(err)
	}
	set := map[string]bool{}
	for _, spec := range specs {
		for _, member := range spec.Members {
			if member.Kind == "attribute" && strings.HasPrefix(member.Name, "on") && strings.ToLower(member.Name) == member.Name {
				set[member.Name] = true
			}
		}
	}
	names := make([]string, 0, len(set))
	for name := range set {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&source, "%q,\n", name)
	}
	source.WriteString("}\n")
	data, err := format.Source(source.Bytes())
	if err != nil {
		panic(err)
	}
	const path = "chrome/152/generated/bootstrap_metadata.go"
	if *check {
		old, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(old, data) {
			panic("bootstrap metadata is stale; run go run ./tools/generatebootstrap")
		}
	} else if err := os.WriteFile(path, data, 0644); err != nil {
		panic(err)
	}
}
